"""empty message

Revision ID: 5d46a7b35003
Revises: dae4ded52bb3
Create Date: 2022-05-24 10:23:37.024872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d46a7b35003'
down_revision = 'dae4ded52bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=320), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
